In [1]:
import numpy as np

arr = np.array([
    [6, -8, 73, -110],
    [np.nan, -8, 0, 94]
])

print("Original Array")
print(arr)

Original Array
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]


In [2]:
arr = np.nan_to_num(arr, nan=0)

print("\nAfter Replacing NaN with 0")
print(arr)


After Replacing NaN with 0
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]


In [3]:
transpose_arr = arr.T

print("\nTranspose Array")
print(transpose_arr)


Transpose Array
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [4]:
arr3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Original Shape:", arr3d.shape)

Original Shape: (2, 2, 2)


In [5]:
new_arr = np.moveaxis(arr3d, 0, 2)

print("\nNew Array")
print(new_arr)

print("\nNew Shape:", new_arr.shape)


New Array
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]

New Shape: (2, 2, 2)


In [7]:
arr = np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]
])

print("Original Array")
print(arr)

Original Array
[[ 1.  2. nan]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


In [8]:
col_mean = np.nanmean(arr, axis=0)

inds = np.where(np.isnan(arr))

arr[inds] = np.take(col_mean, inds[1])

print("\nArray After Replacing NaN")
print(arr)


Array After Replacing NaN
[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [10]:
arr = np.array([4, -3, 7, -1, 9, -6])

print("Original Array")
print(arr)

arr[arr < 0] = 0

print("\nUpdated Array")
print(arr)

Original Array
[ 4 -3  7 -1  9 -6]

Updated Array
[4 0 7 0 9 0]
