In [1]:
import numpy as np

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_1d = np.array([10, 20, 30])

# Combine by stacking vertically (adds the 1D array as a new row)
combined_stack = np.vstack([array_2d, array_1d])
print("Stacked Vertically:\n", combined_stack)

# Combine using broadcasting (adds 1D array to both rows of 2D array)
combined_broadcast = array_2d + array_1d
print("Broadcasted Addition:\n", combined_broadcast)

Stacked Vertically:
 [[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
Broadcasted Addition:
 [[11 22 33]
 [14 25 36]]


In [2]:
arr_2d = np.array([[1, 2], [3, 4]])

# Using flatten
flat_arr = arr_2d.flatten()
print("Flattened array:", flat_arr)  # Output: [1 2 3 4]

Flattened array: [1 2 3 4]


In [3]:
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)  # Output: [5 4 3 2 1]

# To reverse a 2D array along rows: arr[::-1, :]
# To reverse a 2D array along columns: arr[:, ::-1]

Reversed array: [5 4 3 2 1]


In [4]:
matrix = np.array([[5, 12, 3], [9, 1, 14]])

# Get Maximum and Minimum
print("Max value:", np.max(matrix))
print("Min value:", np.min(matrix))

# Find the number of rows and columns (Shape)
rows, cols = matrix.shape
print(f"Rows: {rows}, Columns: {cols}")

Max value: 14
Min value: 1
Rows: 2, Columns: 3


In [5]:
# Specific element selection: matrix[row_index, column_index]
print("Element at row 0, col 1:", matrix[0, 1])  # Output: 12

# Iterating to select/print each individual element
for element in matrix.flat:
    print("Each element:", element)

Element at row 0, col 1: 12
Each element: 5
Each element: 12
Each element: 3
Each element: 9
Each element: 1
Each element: 14


In [6]:
total_sum = 0
for row in matrix:
    for element in row:
        total_sum += element
print("Sum using for loop:", total_sum)

Sum using for loop: 44


In [7]:
a = np.array([10, 20])
b = np.array([2, 5])

print("Addition:", a + b)       # [12, 25]
print("Subtraction:", a - b)    # [8, 15]
print("Multiplication:", a * b) # [20, 100]
print("Division:", a / b)       # [5.0, 4.0]

Addition: [12 25]
Subtraction: [ 8 15]
Multiplication: [ 20 100]
Division: [5. 4.]


In [8]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("--- Iterating using standard nested loops ---")
for block in arr_3d:
    for row in block:
        for item in row:
            print(item, end=" ")
print()

print("\n--- Iterating using np.nditer ---")
for item in np.nditer(arr_3d):
    print(item, end=" ")
print()

--- Iterating using standard nested loops ---
1 2 3 4 5 6 7 8 

--- Iterating using np.nditer ---
1 2 3 4 5 6 7 8 


In [10]:
import numpy as np

arr1 = np.array([3, 4])
arr2 = np.array([1, 0])

avg = (arr1 + arr2) / 2
print("Average of NumPy arrays:\n", avg)

matrix1 = np.array([[10, 20], [30, 40]])
matrix2 = np.array([[15, 20], [35, 45]])

element_wise_avg = (matrix1 + matrix2) / 2
print("Element-wise Average Matrix:\n", element_wise_avg)

combined = np.concatenate((matrix1, matrix2), axis=None)

mean_val = np.mean(combined)
median_val = np.median(combined)

vals, counts = np.unique(combined, return_counts=True)
mode_val = vals[np.argmax(counts)]

print("Mean:", mean_val)
print("Median:", median_val)
print("Mode:", mode_val)

Average of NumPy arrays:
 [2. 2.]
Element-wise Average Matrix:
 [[12.5 20. ]
 [32.5 42.5]]
Mean: 26.875
Median: 25.0
Mode: 20
